version: '3'
services:
  app:
    image: node:14-alpine
    command: sh -c "npm install && npm run build && npm run start"
    ports:
      - "3000:3000"
    expose:
      - "3000"
    working_dir: /app
    volumes:
      - ./:/app
    environment:
     - DD_HOST=datadog-agent
     - DD_LOGS_INJECTION=true
     - DD_ENV=localhost
     - DD_SERVICE=data-correlations-logs
     - DD_VERSION=1.0.0
     - DB=mongodb://mongo:27017/test
    links:
     - mongo
     - datadog-agent
    networks:
      - datadog-network
  mongo:
    image: mongo
    ports:
     - "27017:27017"
    networks:
      - datadog-network
  datadog-agent:
    image: gcr.io/datadoghq/agent:latest
    environment:
      - ENV=test
      - DD_API_KEY=<YOUR_API_KEY>
      - DD_ENV=localhost
      - DD_TRACE_ENABLED=true
      - DD_TRACE_CLI_ENABLED=true
      - DD_LOGS_ENABLED=true
      - DD_APM_ENABLED=true
      - DD_LOGS_INJECTION=true
      - DD_PROFILING_ENABLED=true
      - DD_LOGS_CONFIG_CONTAINER_COLLECT_ALL=true
      - DD_SITE=datadoghq.eu
      - DD_PROCESS_AGENT_ENABLED=true
      - DD_APM_NON_LOCAL_TRAFFIC=true
      - DD_APM_DD_URL=https://trace.agent.datadoghq.eu
    ports:
      - "8126:8126"
      - "8125:8125"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /proc/:/host/proc/:ro
      - /sys/fs/cgroup/:/host/sys/fs/cgroup:ro
    networks:
      - datadog-network
networks:
  datadog-network: